### ISSUE TITLE
Invitation?

### ISSUE THREAD

**Issue by Xushu-Wang** [Open-Quants/Open-Quants#1]
Hi there. I recently received an invitation from you on refining this repo. Could you please inform me where do you find me? Thank you so much! (this is the only way I can reach out to you.

**Comment by SimFG** [comment]
me too. In fact, aren't you curious? This account was registered last week, and it seems that there is no self-introduction, and it seems that there is no real account.

**Comment by kwan-0915** [comment]
@SimFG @Xushu-Wang hello, same here. 

I checked their followers, it seems 90% of them are dead accounts with no comment since 2022 or 2023, I highly doubt if this is some sort of new scam (i hope not).

I suggest just leaving it, and you should check any account that is connected with your email to see if there are any information leaks. 

Stay safe, and block any email that looks like suspicious, have a nice day.

**Comment by Xushu-Wang** [comment]
> @SimFG @Xushu-Wang hello, same here.
> 
> I checked their followers, it seems 90% of them are dead accounts with no comment since 2022 or 2023, I highly doubt if this is some sort of new scam (i hope not).
> 
> I suggest just leaving it, and you should check any account that is connected with your email to see if there are any information leaks.
> 
> Stay safe, and block any email that looks like suspicious, have a nice day.

But the thing is, the website actually looks good tbh. I clicked on a few problems and they are pretty much high quality. It also seems that you guys are quant related. Weirdddddd

**Comment by kwan-0915** [comment]
> > @SimFG @Xushu-Wang hello, same here.
> > I checked their followers, it seems 90% of them are dead accounts with no comment since 2022 or 2023, I highly doubt if this is some sort of new scam (i hope not).
> > I suggest just leaving it, and you should check any account that is connected with your email to see if there are any information leaks.
> > Stay safe, and block any email that looks like suspicious, have a nice day.
> 
> But the thing is, the website actually looks good tbh. I clicked on a few problems and they are pretty much high quality. It also seems that you guys are quant related. Weirdddddd

Yeah, I also check the website, the website looks reasonable, but the group of followers in this account looks like zombies, this is so strange to me. 🫠

**Comment by Guanzhe** [comment]
maybe a new captial of boss is wantting to get through in this career，noting suspicious. good luck！

**Comment by yjian012** [comment]
Well, did any of you get the previous invitation on June 6? Apparently the decided to delete that account and the repo, and created this new account.
![invitaion](https://github.com/Open-Quants/Open-Quants/assets/14990060/4303f4aa-2042-474d-a1c6-e145a94cabeb)
Interestingly, it seems that they forgot to change the profile picture for this account. The previous one is the same as the website.
There are a few other sus things as well, but I don't know if it's worth mentioning them. I wonder if they'll just delete this repo as well? The issues will be gone with it anyway, right?

**Comment by bblurock** [comment]
Have to say, this is good shady marketing hack…

**Comment by Open-Quants** [comment]
sorry guys yeah its just marketing
but its a great site with lots of free questions
We're really working hard on growing it so any feedback would help!

**Comment by kwan-0915** [comment]
> sorry guys yeah its just marketing but its a great site with lots of free questions We're really working hard on growing it so any feedback would help!

no one does marketing like this, you are using the system to send junk mail this is abuse or spam, thanks for your confess, will send abuse or spam report to GitHub team ;)
